### ISSUE TITLE
Not working in Postman

### ISSUE THREAD

**Issue by chiragthummar** [NotCookey/Lexica.art#1]
Hi,
I have tried in postman it's not working and giving 500 internal server error

**Comment by NotCookey** [comment]
> Hi, I have tried in postman it's not working and giving 500 internal server error

Lexica's Api routes are current for the project. The script actually functions if you attempt using it. The problem could lie elsewhere since you require additional parameters, such as an uuid4 and a random string of length 20, if you're trying to post to one of the routes using a different programme. The script manages all that by default.


It would be helpful if you could give a little more information about the where you encountered and how it happened.
